language: elixir

matrix:
  include:
    - otp_release: 19.0
      elixir: 1.3.4
    - otp_release: 19.0
      elixir: 1.4.0
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.5

sudo: false
